### ISSUE TITLE
Check Beacon returns an error

### ISSUE THREAD

**Issue by misha-l** [rainlab/deploy-plugin#11]
Hello,
After uploading beacon to shared hosting when I click on "Check Beacon" the following error appears:

"Return value of RainLab\Deploy\Models\Server::createNonce() must be of the type int, string returned" on line 254 of E:\xampp\htdocs\october7\plugins\rainlab\deploy\models\Server.php

Everything is latest version:
OctoberCMS build 2.1.2
Deploy version 1.0.4

Local PHP Version 7.4.8

How can I fix this?
Thank you

**Comment by daftspunk** [comment]
Hi, this is an oversight in the design that has only appeared in your environment.

Try changing the code found in this commit and let me know if it fixes the issue for you:

42a3a85f484a5eff2d1b2b84feac4dfd3f10e8c0

If that fixes it, we will ship a new release for it.

Thanks
