### ISSUE TITLE
remove plugins?

### ISSUE THREAD

**Issue by Hessel91** [rainlab/deploy-plugin#15]
Hi, because there is no ability to add artisan commands, how can I remove installed plugins?
I can install them with deploy but I have to use FTP or direct admin in order to remove them, correct?

**Comment by artistro08** [comment]
Yeah that's correct. I recently ran into this problem. Essentially you just need to delete them from the folder and drop the corresponding tables in the database. Dropping the tables is crucial because if you don't, migrations won't run correctly when you deploy.
