### ISSUE TITLE
Deploy Installation, Error at Migration step

### ISSUE THREAD

**Issue by pgarnek** [rainlab/deploy-plugin#17]
Hello!

I can't install october on production environment usind deploy plugin.
Beacon created, uploaded, found in my local october backend, when i click Install October CMS...
![2021-09-06 02_53_47-Manage Server _ October CMS — Mozilla Firefox](https://user-images.githubusercontent.com/6490500/132146927-7c044804-bf4c-4fb1-bfbf-cf3b4054ce38.png)

after review setting
![2021-09-06 02_54_46-Manage Server _ October CMS — Mozilla Firefox](https://user-images.githubusercontent.com/6490500/132146941-9d40349e-4dcd-446d-8c6c-ea1ffe7d6eb4.png)

installation process goes trough many steps, but when "Migration" text shows up for a while, immediatelly comes error notification:
![obraz](https://user-images.githubusercontent.com/6490500/132146979-0a68ae53-8a6f-47af-b0a8-8b25b89f0f19.png)

"Try Again" won't go untill i delete 3 tables created during installation: 
![obraz](https://user-images.githubusercontent.com/6490500/132147023-02910420-a78d-4df8-a8ff-fa0ba40b10e7.png)

but after all, same error shows up.
I don't have possibility to install via composer on my server, that's why i've decided to go with deploy plugin.

I found many situations with same error, the solution was to change encoding in conf/database.php, but i haven't this possibility before installation.

please help me to find a solution or give possibility to change encoding during installation process for a try, maybe that would come and go? :/

**Comment by pgarnek** [comment]
I've found a workaround to go trough this problems:

- after "Update Failed" error as above, when i Refresh plugin page, it show's me october CMS is installed (strange behavior)
- in next step i'm removing all database tables which were created (3, as on above screen)
- then i modify conf/database.php changing encoding like here: https://github.com/octobercms/october/issues/1927
- then when I click Deploy button and select any plugin, without vendor and configuration files
Deploy process runs migration, goes trough migration, after all ends successful.

Once there were no users in database, so i've created one and set password with attlasian october:passwd command.

Anyway - strange behavior, smells like issue to solve :)

**Comment by daftspunk** [comment]
Hi @pgarnek 

This is likely caused by the new [Database Requirements of October 2.0](https://octobercms.com/support/article/rn-13#database-requirements). There is a recommended approach linked in the guide.

Glad you got it solved!

---

#### Database Requirements

The new minimum supported version for MariaDB is 10.2 and MySQL is 5.7.7, however, older versions will still work. If you wish to continue to use lower versions, ensure the following is added to your database configuration under the key `database.connections.mysql`.

```
'varcharmax' => 191,
```

**Comment by pgarnek** [comment]
thanks @daftspunk !
should i set back `charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci'` when 'varcharmax' is set to 191 ?

**Comment by daftspunk** [comment]
Both solutions are fine, but are not necessary to be used together. i.e One or the other, not both
