### ISSUE TITLE
Max Upload Size

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/deploy-plugin#19]
php.ini is setting `upload_max_filesize = 256M`

but the deploy does not folow through

![image](https://user-images.githubusercontent.com/2263496/134634077-a620cf52-82e8-4801-9a48-d79421f689b5.png)

any insights?

**Comment by kevinvermeulenn** [comment]
@daftspunk , I've the same issue as above. I tried with 20mb and even with 1000mb it won't work. 
Could you support?

**Comment by chrisvidal** [comment]
@kevinvermeulenn double-check the `php.ini` on the server side, it happened to me and I realised that Apache was using another php.ini.
