### ISSUE TITLE
Add UI for running Artisan commands

### ISSUE THREAD

**Issue by Hessel91** [rainlab/deploy-plugin#21]
Hi, how can I change the license key with deploy?
Or where can I find the correct place to edit this in my webserver files?
on localhost I can use Project:set however the license key does not change with deployment.

**Comment by Hessel91** [comment]
Hi, the output in the console is not as expected. 
"Call to undefined function October\Rain\Process\exec()"
What could cause this error?

**Comment by daftspunk** [comment]
Hey @Hessel91 

You probably have the `shell_exec`, `exec` and etc. functions disabled in your php.ini file.

What you could do is create a PHP info file and check if this is the case:

```
<?php

phpinfo();

?>
```

Then visit the file via your browser and look for `disable_functions`. If this is the case edit your php.ini file and remove the `shell_exec` functions from the `disabled_functions` list and then restart your Apache service.

I hope this helps!

**Comment by Hessel91** [comment]
Thanks, @daftspunk , solved the issue now.
