### ISSUE TITLE
Can't generate RSA key in french language

### ISSUE THREAD

**Issue by Ladylain** [rainlab/deploy-plugin#22]
Hi there, 

i'm using October v2.0 and i'm french, 
i was trying to generate an RSA key but when i click on "generate new" i have this javascript error in the console, due to the french translation of the waiting text. 

![image](https://user-images.githubusercontent.com/5721178/137329037-c907f939-7836-447d-b1fd-20fa1c1d5301.png)

I have succeed to generate by changing my backend lang. but i send this issue to resolve this for maybe others french users. 

Best, 
Lucas

**Comment by daftspunk** [comment]
Hi Lucas,

Thanks for this report. This will be fixed in the next release.
