### ISSUE TITLE
Update Failed Unspecified error from beacon

### ISSUE THREAD

**Issue by pangeaos** [rainlab/deploy-plugin#23]
I have a shared hosting in Siteground. I have downloaded the files in the server but I got this error.

Versions

octobercms = 2.1.17
deploy = 1.0.4
php = 7.4.24

![Screen Shot 2021-10-21 at 8 09 11 PM](https://user-images.githubusercontent.com/221474/138382823-2a889080-dc52-499b-b0f4-bd2d86ee6f61.png)

**Comment by daftspunk** [comment]
Hi @pangeaos 

Could you try adding the following:

1. Open the server in the backend
1. Add `?debug=1` to the end of the URL 
1. Try the task again
1. Check the storage/logs log file for the debug contents

Thanks

**Comment by pangeaos** [comment]
I'm seeing this error.

[system.log](https://github.com/rainlab/deploy-plugin/files/7394062/system.log)

`<h1 class="title title--regular title--size-large title--weight-bold">Access Denied</h1>
                <p class="title title--subtitle title--size-semimedium title--weight-normal">The page you are trying to access is restricted due to a security rule.<br/><br/>
                    If you believe that this security rule is affecting the normal operation of your website, contact your hosting provider with detailed instructions how to recreate this error.
                </p>`
