### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by mcglynnmark** [rainlab/deploy-plugin#26]
| PDOException: SQLSTATE[42S02]: Base table or  view not found: 1146 Table 'october_main.rainlab_deploy_servers'  doesn't exist in  C:\laragon\www\myoctober\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:82
-- | --

**Comment by daftspunk** [comment]
Hi @mcglynnmark 

After installing the plugin, migrate the database using the following command:

```
php artisan october:migrate
```

This should create the missing table and fix the error.

I hope this helps!
