### ISSUE TITLE
Sites deployed yield an error through Swiftmailer. 

### ISSUE THREAD

**Issue by mcglynnmark** [rainlab/deploy-plugin#27]
Swift_RfcComplianceException: Address in mailbox given [] does not comply with RFC 2822

Event Log shows: "Swift_RfcComplianceException: Address in mailbox given [] does not comply with RFC 2822, 3.6.2. in /var/www/vhosts/xx.xx/httpdocs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355

Any thoughts on this?

**Comment by daftspunk** [comment]
This error is unrelated to the Deploy plugin. 

The error suggests that your app is trying to send an email to an invalid email address. If the email contains a space in it (even at the beginning or the end), this error will occur. One thing to check, make sure that the email address used has been trimmed with the `trim()` PHP function. It is difficult to offer further advice without knowing the source or trigger of the error.

I hope this helps!

**Comment by mcglynnmark** [comment]
Hello Sam,

Thank you kindly, this problem is proving difficult to diagnose.

Would you be willing to advise via email directly?

Regards,

Mark McGlinn
