### ISSUE TITLE
Beacon Unreachable

### ISSUE THREAD

**Issue by kevinvermeulenn** [rainlab/deploy-plugin#29]
I've done all steps that are necessary. Uploaded the unzipped files to server subdomain.domain.com (also tried https://subdomain.domain.com). The status of the beacon keeps unreachable. 

How to solve this?

**Comment by daftspunk** [comment]
Hi @kevinvermeulenn 

Try this too debug the outcome:

1. Add `?debug=1` to the end of the URL in the backend
2. Click Check beacon
3. Check the log file in **storage/logs** to see what the server is responding with

I hope this helps!

**Comment by kevinvermeulenn** [comment]
hanks for your support, @daftspunk! 

I've succeed to get the log file in the **storage/logs**.
Seems that I was missing the **/** at the end of the URL.

**Comment by daftspunk** [comment]
Ah yes, this can be caused by a redirect happening at your server. When it redirects to include a trailing slash then the beacon message can be lost. 

Thanks for reporting back
