### ISSUE TITLE
Install archive can't bundle up because of empty files

### ISSUE THREAD

**Issue by FlusherDock1** [rainlab/deploy-plugin#3]
After succesfully installing beacon my deployment ready to be sent to remote server and install fresh october.

But on step of building archive there is error: 
"file_put_contents(D:\laragon\www\october\storage\temp\60acd51bc6ce8\): failed to open stream: No such file or directory" on line 133 of D:\laragon\www\october\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php

gist: https://gist.github.com/FlusherDock1/58405befd8906d62bd54f66ce063db97

I found that this section has empty 'files' array, and it tries to create empty file with empty name.
```
// Build files
$files = $options['files'] ?? [];
foreach ($files as $filename => $contents) {
    file_put_contents($tmpPath . '/' . $filename, $contents);
}
```

**Comment by FlusherDock1** [comment]
It's not just "empty" 

this is var dump of  $options['files']
array(1) { [""]=> string(0) "" } ""

**Comment by daftspunk** [comment]
Hey, see if this will fix it fcd686dd276b7bf0a443190dcc45240eb6d32f70

**Comment by FlusherDock1** [comment]
Now it goes to Deploying Core Archive and fails on it with error Missing filename or filehash

**Comment by daftspunk** [comment]
What version of PHP are you running?

**Comment by FlusherDock1** [comment]
I see where this is going, deployment server had 7.1 php, changed to 7.3 and everything worked!
