### ISSUE TITLE
Unable to connect beacon

### ISSUE THREAD

**Issue by pivisions** [rainlab/deploy-plugin#32]
I have Godaddy Shared hosting. 
Uploaded the files on server. I am able to reach the link via browser. 
But in backend it still shows unable to connect beacon. 
Tried everything possible, but could not figure out the cause.

**Comment by daftspunk** [comment]
Hi @pivisions 

You can perform more troubleshooting by capturing the raw response from the server or beacon. To capture the raw response from the beacon, do the following.

1. Add `?debug=1` to the end of the URL in the backend.
1. Click Check Beacon or perform the deployment action again.
1. Check the log file in **storage/logs** to see what the server is responding with.

This should hopefully provide some insight into why the response was not accepted.

**Comment by pivisions** [comment]
Still not working. 
Files are uploaded here:
http://seagullschool.pivisions-sites.com

I added debug=1, but it does not log any error in the logs. 
![image](https://user-images.githubusercontent.com/1911171/147208580-883bb196-58a7-4e22-8268-dae76f577f05.png)

Not sure what I am doing wrong here!!

**Comment by daftspunk** [comment]
HTTPS should not pose any significance. I see that you have entered the URL as: `http://seagullschool.pivisions-sites.com?debug=1`

Try entering it as: `http://seagullschool.pivisions-sites.com/`

The trailing slash (`/`) may be important. To update the server click the (update) link next to the URL.

I hope this helps!

**Comment by pivisions** [comment]
Nope, not working. 
![image](https://user-images.githubusercontent.com/1911171/147220810-54bdef16-d5cb-464c-9a07-80fe8d72e458.png)





Error Log
October\Rain\Network\Http Object
(
    [url] => http://seagullschool.pivisions-sites.com/?XOB_CMD=healthCheck&XOB=2b16322c6ae72a5ba0516e1f263b9375&XOB_SIGNATURE=kEepueKk1Q%2F%2Boi8beYgk%2Fb9%2BfgkHRTrtE1DSjQSJmaKK%2F5aO3cH5el0C1cc0VYuU%2FCqV1LjaZhb9kwTzaFtzDx829wcg5G86HPmjNzxRcVWQTY3xu0kqNT3kaO8hqQG%2F4wgLLbWyV20Q16k45rK3f5HungCqW1KCb1C8jBzCU5GTsCz7GkZ1jN%2FslPwANPhPZF2uIqyrus%2BJc%2BKT2Qlh46UcLLhMMSrIMItqxQBfPJIc62AWZ5tLLj%2Blw8RQyEWmsdXn9gmYHEkwq48CvLxVUoH5qs1aJmuftWNs65YfSXOm4wrYfjYAmPf9Zytd45rBFshEZD7e%2F2Mp5Qb43wcxlQ%3D%3D
    [method] => POST
    [headers] => Array
        (
            [HTTP/1.1] => 200 OK
            [Date] => Thu, 23 Dec 2021 09:36:21 GMT
            [Server] => Apache
            [X-Powered-By] => PHP/8.0.13
            [Upgrade] => h2,h2c
            [Connection] => Upgrade
            [Vary] => Accept-Encoding
            [Transfer-Encoding] => chunked
            [Content-Type] => text/html; charset=UTF-8
        )

    [headerCallbackFunc] => 
    [body] => Missing vendor files, try running "composer install" to install October CMS

    [rawBody] => HTTP/1.1 200 OK
Date: Thu, 23 Dec 2021 09:36:21 GMT
Server: Apache
X-Powered-By: PHP/8.0.13
Upgrade: h2,h2c
Connection: Upgrade
Vary: Accept-Encoding
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8

Missing vendor files, try running "composer install" to install October CMS

    [code] => 200
    [info] => Array
        (
            [url] => http://seagullschool.pivisions-sites.com/?XOB_CMD=healthCheck&XOB=2b16322c6ae72a5ba0516e1f263b9375&XOB_SIGNATURE=kEepueKk1Q%2F%2Boi8beYgk%2Fb9%2BfgkHRTrtE1DSjQSJmaKK%2F5aO3cH5el0C1cc0VYuU%2FCqV1LjaZhb9kwTzaFtzDx829wcg5G86HPmjNzxRcVWQTY3xu0kqNT3kaO8hqQG%2F4wgLLbWyV20Q16k45rK3f5HungCqW1KCb1C8jBzCU5GTsCz7GkZ1jN%2FslPwANPhPZF2uIqyrus%2BJc%2BKT2Qlh46UcLLhMMSrIMItqxQBfPJIc62AWZ5tLLj%2Blw8RQyEWmsdXn9gmYHEkwq48CvLxVUoH5qs1aJmuftWNs65YfSXOm4wrYfjYAmPf9Zytd45rBFshEZD7e%2F2Mp5Qb43wcxlQ%3D%3D
            [content_type] => text/html; charset=UTF-8
            [http_code] => 200
            [header_size] => 227
            [request_size] => 656
            [filetime] => -1
            [ssl_verify_result] => 0
            [redirect_count] => 0
            [total_time] => 0.359666
            [namelookup_time] => 0.001116
            [connect_time] => 0.078481
            [pretransfer_time] => 0.078548
            [size_upload] => 70
            [size_download] => 76
            [speed_download] => 211
            [speed_upload] => 194
            [download_content_length] => -1
            [upload_content_length] => 70
            [starttransfer_time] => 0.359609
            [redirect_time] => 0
            [redirect_url] => 
            [primary_ip] => 184.168.119.95
            [certinfo] => Array
                (
                )

            [primary_port] => 80
            [local_ip] => 192.168.1.4
            [local_port] => 61947
            [http_version] => 2
            [protocol] => 1
            [ssl_verifyresult] => 0
            [scheme] => HTTP
            [appconnect_time_us] => 0
            [connect_time_us] => 78481
            [namelookup_time_us] => 1116
            [pretransfer_time_us] => 78548
            [redirect_time_us] => 0
            [starttransfer_time_us] => 359609
            [total_time_us] => 359666
        )

    [requestOptions] => 
    [requestData] => Array
        (
            [XOB_PAYLOAD] => eyJjbWQiOiJoZWFsdGhDaGVjayIsIm5vbmNlIjoxNjQwMjUyMTgxNn0=
        )

    [requestHeaders] => 
    [argumentSeparator] => &
    [streamFile] => 
    [streamFilter] => 
    [maxRedirects] => 10
    [redirectCount:protected] => 
    [hasFileData:protected] => 
)

**Comment by pivisions** [comment]
Nevermind. I was able to fix it. 
I was using beacon zip of another server entry. I thought they were some standard files. 
Downloaded the new beacon files from the new server entry. And it got connected. 
Thanks for your help.

**Comment by daftspunk** [comment]
Glad to hear you got it sorted!

**Comment by daftspunk** [comment]
> I was using beacon zip of another server entry. I thought they were some standard files.

BTW - The beacon files are directly linked to the Deployment Key, so you can reuse the beacon files if you share the same Deployment Key across all the servers.
