### ISSUE TITLE
Beacon failing with internal server error

### ISSUE THREAD

**Issue by pashasiraja** [rainlab/deploy-plugin#33]
I've got a simple shared host with a local development environment with OctoberCMS installed.

When I check the beacon it returns this PHP error:
<b>Parse error</b>:  syntax error, unexpected '?' in <b>***REDACTED***/webroot/bootstrap/beacon.php</b> on line <b>40</b><br />

PHP 7.4 with https

Can anyone help please?

**Comment by daftspunk** [comment]
Hi @pashasiraja 

Wishing you a happy new year. Sorry to hear you are having difficulty with this.

Line 40 contains a "null coalescing operator" that was added in PHP 7.0 and onwards. This suggests your server may be running an incompatible version of PHP. Please check with your service provider on how to ensure that the web server uses PHP 7.4, sometimes it can be customized per website.

I hope this helps!

**Comment by pashasiraja** [comment]
Hi, I've made sure that the server is running php v7. 4, would you be able
to point at any specific setting / module / extension that I could enable
or check to make it work?

Thanks!

**Comment by daftspunk** [comment]
Using this code

```
<?php

echo $a ?? 'a variable is not defined';
```

The exact error can be reproduced here using PHP 5.6.29:
- http://sandbox.onlinephpfunctions.com/code/f786b52fcaede7e8470a1882cb89d95564186a03

> <b>Parse error</b>:  syntax error, unexpected '?' in <b>[...][...]</b> on line <b>5</b><br />

Notice the error does not occur using PHP 7.0.1:
- https://sandbox.onlinephpfunctions.com/code/f786b52fcaede7e8470a1882cb89d95564186a03

> a variable is not defined

This confirms that your server is not using PHP 7.4. Please contact your web host for support with switching the version. There is no module, the syntax error comes directly from the PHP version. I'm sorry we can't be of more assistance.

Best of luck!
