### ISSUE TITLE
Deploying October v2.2 Takes two Core deploys

### ISSUE THREAD

**Issue by artistro08** [rainlab/deploy-plugin#34]
So I deployed with OctoberCMS after the new v2.2 update and it crashed the site. This was the error that I got:

```
ErrorException: trim() expects parameter 1 to be string, array given in /var/www/html/procedural-tech/modules/media/classes/MediaLibrary.php:490

```

Not sure why, but once I deployed again, everything was fixed.

**Comment by daftspunk** [comment]
This can sometimes happen when too many files change on the server. The second deployment would have corrected any data irregularities and is a good solution to the issue.

As a side path, I traced this specific exception and fixed it in the next release (v2.2.4)
