### ISSUE TITLE
Storage does not work after major update

### ISSUE THREAD

**Issue by maki3000** [rainlab/deploy-plugin#35]
I recently did a major update from october v1 to v2 with the deploy plugin.

Most if it worked well, but the storage seems to be broken for my plugins when I try to upload images, which I attached to the 'System\Models\File'.

It throws me a javascript error:
```
GET https://dassoz.ch/storage/app/uploads/public/623/074/dea/thumb_7_190_170_0_0_crop.jpg
[HTTP/2 404 Not Found 229ms]
```

I'm using october version 2.2.11 and PHP 7.4

I thought, that was because of the still active resize plugin. I removed that manually (deleted the files and the entry in the database) with no luck.

On the local setup everything is working fine. I assume, there is a problem with the old storage folders and files on the production page.

**Comment by daftspunk** [comment]
Hey @maki3000 

It could be a permission problem, try setting these environment variables to see if it helps:

```
DEFAULT_FILE_MASK=775
DEFAULT_FOLDER_MASK=775
```

**Comment by maki3000** [comment]
Hey @daftspunk 

That unfortunately didn't work.

Could it be that I would need to run:
```php artisan storage:link```

But if so, how could I do that on my shared hosting without SSH?

**Comment by maki3000** [comment]
Please forget about my last comment, that was not the issue.

I just didn't deploy the config file. Sorry for that!

Now that I did this step, the upload works fine.
