### ISSUE TITLE
Can't deploy because of deleted plugins from the marketplace

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/deploy-plugin#39]
My project used to use a plugins available from the marketplace (Synder.Analytics)
The author seems to have remove it and is causing some issue for the deploy plugin.
Even though I removed the plugins from my project, I also removed the plugin from my local dev and I am facing this issue while attempting to deploy on muy staging server.

![image](https://user-images.githubusercontent.com/2263496/172293947-6406afd1-ae57-47d9-8688-3fd24b751bf5.png)

**Comment by chrisvidal** [comment]
mmm...seems like this message is coming from the plugin itself in its boot method.

```php
$installedVersion = PluginVersion::where('code', 'Synder.Analytics')->first();
        if ($installedVersion === null || !version_compare($installedVersion->version, self::VERSION, '=')) {
            if (php_sapi_name() === 'cli') {
                return;
            }
            throw new SystemException('Please run "php artisan october:migrate" to install and update Synder.Analytics.');
        }
```

**Comment by daftspunk** [comment]
Hey @chrisvidal 

You may need to remove the plugin files manually from the remote server. October CMS has a "non-destructive" policy so doesn't offer this feature.

I hope this helps.

**Comment by chrisvidal** [comment]
yes, I was taken by surprise by the deploy plugin as it does not really replace what has been already deployed once.
so after one failed deploy attempt, I removed the plugin locally and deployed again thinking that the deploy will re-deploy everything. But that is not the case.
problem solved by removing the plugin manually on remote server. thanks
