### ISSUE TITLE
Small Bug: AJAX Loader doesn't appear in right position

### ISSUE THREAD

**Issue by artistro08** [rainlab/deploy-plugin#40]
See Screenshot below. 

![image](https://user-images.githubusercontent.com/6427230/174700856-5e69463e-a3f4-4fb2-9642-268fe618ab57.png)

**Comment by daftspunk** [comment]
To confirm--

Expecting: One progress bar to be displayed

Actual: Two progress bars are displayed

Is it correct?

**Comment by daftspunk** [comment]
Ah, I see! The second progress bar isn't animating. 

This will be fixed in v3.0.55+

Thanks!
