### ISSUE TITLE
Have a problem when try to deploy 

### ISSUE THREAD

**Issue by jaans007** [rainlab/deploy-plugin#42]
A valid response from a beacon was not found. Add ?debug=1 to your URL, try again and check the logs (Code: 0)

**Comment by daftspunk** [comment]
Hi @jaans007 

Sometimes you may see an error that a valid response from a beacon was not found.

The first thing to try is the "Check Beacon" link to make sure the beacon is **Active**, if it says **Unreachable**, try downloading the beacon files and uploading them again to your server.

You can perform more advanced troubleshooting by capturing the raw response from the server or beacon. To capture the raw response from the beacon, do the following.

1. Add `?debug=1` to the end of the URL in the backend.
1. Click Check Beacon or perform the deployment action again.
1. Check the log file in **storage/logs** to see what the server is responding with.

This should hopefully provide some insight in to why the response was not accepted.

**Comment by jaans007** [comment]
I try to insert in to url http://myoctober.test/backend/rainlab/deploy/servers/manage/1?debug=1 and in to shared hosting in storage/logs nothing

**Comment by daftspunk** [comment]
The log will appear in your local environment, not on the remote host.

**Comment by daftspunk** [comment]
Hopefully, you got this resolved. If you still need support with this, feel free to email the helpdesk: https://octobercms.com/contact
