### ISSUE TITLE
Some language packs based on "'system:: lang. updates" have expired

### ISSUE THREAD

**Issue by ZhiweiWu0425** [rainlab/deploy-plugin#44]
In October3. x, some keys calling system language in plug-ins are missing.
eg：
system::lang.updates.update_failed_label
system::lang.updates.retry_label
![image](https://user-images.githubusercontent.com/89636889/196933430-5a78aa35-130a-4646-8e1e-cf5fa3232125.png)

**Comment by daftspunk** [comment]
This should be fixed by 1f53f5d63666cdd10a0409ab8f943878c699fbde
