### ISSUE TITLE
Beacon ok, but update failed

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/deploy-plugin#47]
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/2263496/221330358-ae8e09c8-432a-476d-8a29-28ccda7c2abc.png">

doing a `/backend?debug=1` returns an error 404

browsing the domain gives `Missing vendor files, try running "composer install" to install October CMS`

**Comment by daftspunk** [comment]
The URL should be: `/admin/rainlab/deploy/servers/manage/1?debug=1`. Then check the system.log file for the error.

**Comment by chrisvidal** [comment]
no luck with this url as well, whether I use `/admin` or `/backend`

<img width="869" alt="image" src="https://user-images.githubusercontent.com/2263496/221332616-5f4e796b-1167-4a26-a673-c894b7a3d13e.png">

**Comment by chrisvidal** [comment]
dont see any particular error

**Comment by daftspunk** [comment]
Looks like an empty response, which means a suppressed error. Check the PHP error log for more detail.

**Comment by chrisvidal** [comment]
mmm dont seem to have one php error log on my local

**Comment by chrisvidal** [comment]
ok, I spotted this `Class \"PDO\" not found"`

**Comment by daftspunk** [comment]
The `PDO` extension is indeed a requirement to run October CMS and interact with the database.
