### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/deploy-plugin#48]
when debugging, I am receiving this error from php8.1 on Ubuntu 22.4

I keep increasing the `upload_max` value but always this error is showing up.

```
[body] => {"error":"Server did not accept the upload (Max: 13512MB)"}
```

**Comment by daftspunk** [comment]
Hi @chrisvidal , 

The `upload_max_filesize` looks adequate. Check `post_max_size`, and the web server error log for the exact error message.

**Comment by chrisvidal** [comment]
oh ya, I forgot the little sister 👍 thanks @daftspunk
