### ISSUE TITLE
Question: deploy a OC v2 onto an existing OC v1

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/deploy-plugin#49]
What is happening to the current plugins in the OC v1 website?
the new plugins in the new version?
the eventual deleted/disabled plugins in the new version?

Does the deploy run the migration where the plugins were at?

**Comment by daftspunk** [comment]
All plugins move migrations forward, so the path from v1 → v2 → v3 should be included in the latest plugin codebase. Some plugins may not be compatible but usually require minor code adjustments, usually related to Laravel changes. The deploy plugin is simple and will deploy what is found in the local environment.
