### ISSUE TITLE
Plugin deployment failed

### ISSUE THREAD

**Issue by cyril-design** [rainlab/deploy-plugin#50]
Hi.
Since a while i cannot activate a new plugin on remote server.
The files are successfully uploaded to the remote server, migrate process is ok, clearing cache... etc.
But there is not activation in remote october admin (no entry in system_plugin_versions table).

Any ideas ?

**Comment by daftspunk** [comment]
Hi @cyril-design 

One thing to check is dependencies. If a plugin requires another (`$require` property in the Plugin.php file), it may not load or migrate if that plugin is missing.

**Comment by cyril-design** [comment]
I checked: the plugins do not require any particular dependencies.
How are the plugins loaded in OctoberCMS ?

**Comment by daftspunk** [comment]
The class `System\Classes\PluginManager` is responsible for loading the plugins and it stores a manifest file in **storage/cms/manifest.php** when debug mode is off.

Try this command: `php artisan plugin:list` to see if it appears in the list

Hopefully some of this helps with debugging.

**Comment by cyril-design** [comment]
Thanks for your reply Daft.
Plugin doesn't appear in the manifest list.
I add my plugin in the manifest :
```php
'initbiz\\seostorm' => 'initbiz/seostorm',
``` 
And redeploy it via Deploy and it works !

**Comment by daftspunk** [comment]
Great! Glad you got it solved.

Clearing cache should solve this because it deletes the manifest file, from there it is rebuilt to include all plugins found in the file system.
