### ISSUE TITLE
A valid response from a beacon was not found

### ISSUE THREAD

**Issue by kikobalco** [rainlab/deploy-plugin#6]
Hi folks,
I'm trying to make this plugin working on my localhost with deployment to test server on shared hosting,
but I'm getting this error during "Deploy Vendor Archive" phase

```
Update Failed
A valid response from a beacon was not found. Add ?debug=1 to your URL, try again and check the logs (Code: 0)
```

First I got it few times during Installation of OctoberCMS to remote server.
Whole invalid response looks like this (I deleted some parts - urls and local paths, because project needs to stay private for now):

```
October\Rain\Network\Http Object
(
    [url] => <deleted>
    [method] => POST
    [headers] => Array
        (
        )
    [headerCallbackFunc] =>
    [body] =>
    [rawBody] =>
    [code] => 0
    [info] => Array
        (
            [url] => <deleted>
            [content_type] =>
            [http_code] => 0
            [header_size] => 0
            [request_size] => 705
            [filetime] => -1
            [ssl_verify_result] => 0
            [redirect_count] => 0
            [total_time] => 71.703961
            [namelookup_time] => 0.00075
            [connect_time] => 0.028687
            [pretransfer_time] => 0.115696
            [size_upload] => 11723079
            [size_download] => 0
            [speed_download] => 0
            [speed_upload] => 163494
            [download_content_length] => -1
            [upload_content_length] => -1
            [starttransfer_time] => 0.115717
            [redirect_time] => 0
            [redirect_url] =>
            [primary_ip] => 37.9.175.131
            [certinfo] => Array
                (
                )
            [primary_port] => 443
            [local_ip] => 10.0.1.101
            [local_port] => 60496
            [http_version] => 0
            [protocol] => 2
            [ssl_verifyresult] => 0
            [scheme] => HTTPS
            [appconnect_time_us] => 115573
            [connect_time_us] => 28687
            [namelookup_time_us] => 750
            [pretransfer_time_us] => 115696
            [redirect_time_us] => 0
            [starttransfer_time_us] => 115717
            [total_time_us] => 71703961
        )
    [requestOptions] =>
    [requestData] => Array
        (
            [file] => CURLFile Object
                (
                    [name] => <deleted>
                    [mime] =>
                    [postname] =>
                )
            [filename] => e681426c83ca9f99226da49905ac9b7a
            [filehash] => e556fd8a50fb6bfc7d646c4e9bb6fd56
        )
    [requestHeaders] =>
    [argumentSeparator] => &
    [streamFile] =>
    [streamFilter] =>
    [maxRedirects] => 0
    [redirectCount:protected] =>
    [hasFileData:protected] => 1
)
```

In the middle of writing this post it suddenly started working and I succesfully installed OctoberCMS, but it's again giving this error when trying to "Deploy to Server". Again during "Deploy Vendor Archive"

Some of my shared hosting PHP settings looks like this:
```
max_execution_time
600s
memory_limit
512MB
upload_max_filesize
256MB
post_max_size
256MB
```

Do you have any idea, what can cause this?

**Comment by kikobalco** [comment]
UPDATE:
After couple of "Try again" hits it always works, so basically it's working, but still don't know the reason behind this error :)

**Comment by PictureElement** [comment]
I had the same issue. I solve it by specifying PHP version in .htaccess like so:

<IfModule mime_module>
  AddHandler application/x-httpd-ea-php74 .php .php7 .phtml
</IfModule>

**Comment by daftspunk** [comment]
If I had to guess, due to the repeated attempts being successful, your server may be hitting its maximum execution time and returning an empty response (error: 0). Try increasing this PHP setting to see if it helps

```
max_execution_time = 10
```

**Comment by kikobalco** [comment]
I also thought about execution time, but it's set to 600s by default by my hosting provider. And I was getting that error much sooner, after cca 1-2 min of deploy.

**Comment by daftspunk** [comment]
Try checking the error logs for some kind of failure that is not being transmitted with the response.
